### ISSUE TITLE
No bannertext on homepage

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#143]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the
following:
    * Reproduced the problem with clear cache.
    * (If running the application locally:) Made sure your running the newest version on the development branch
    * Checked that your issue isn't already filed: https://github.com/UTNkar/moore/issues

### Description

Adding bannertext doesn't work. Nothing shows up. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
Seems to be an issue in the admin menu. The Swedish text attribute is not added to the admin menu and thus not shown.
