### ISSUE TITLE
Adding picture/description

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#147]
When adding picture and description the format it comes out in when doing the preview looks really weird. The pictures zooms alot and the text is in the middle taking up a lot of space no matter how much text you write. 

![image](https://user-images.githubusercontent.com/29704138/27686622-e4c0b252-5cd3-11e7-929a-83de7fd4aec2.png)

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
This is because of responsive design. In the Image + description block, the size of the picture is determined by the height of the description block and the width of the screen.

If you want the determine the size of the picture yourself, you have to use the Paragraph options.
