### ISSUE TITLE
Font sizes of Headers in StreamBlocks

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#153]
### Description

The different font size options are differently sized every time using it. When pressing H5, sometimes its the biggest and sometimes its the smallest. Still don't know which one is which. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
Headers should range from biggest, H1, to smallest, H5, if this is not the case then a mistake has been made in the style sheets. Please provide the places in which this is not the case.

**Comment by Dekker1** [comment]
The problem was a odd occurrence in the editor. Closed for now
