### ISSUE TITLE
Images crashed

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#162]
### Description

Cant upload images.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
https://stackoverflow.com/questions/45029590/wagtail-admin-images-crash-how-to-get-more-crash-information

**Comment by Dekker1** [comment]
https://sentry.io/uppsala-teknolog-och-naturveta/moore/issues/309900785/
