### ISSUE TITLE
Navigation wrap around

### ISSUE THREAD

**Issue by Dekker1** [UTNkar/moore#171]
### Description

Currently when the window gets too small, but not small enough to be the mobile menu, the profile menu wraps around. Somebody with more CSS knowledge should find a good solution to this.

![screen shot 2017-07-14 at 11 24 07](https://user-images.githubusercontent.com/1564252/28206658-0e426634-6887-11e7-9dda-f9160f60a732.png)

### Steps to Reproduce

1. Go to home page
2. Make your window smaller

**Comment by don-harris** [comment]
I will try and fix this !

**Comment by Dekker1** [comment]
Hey Don!

I'm glad to see someone is one this! My intuition would be to crop the menu when necessary and display an "More" dropdown menu.

Feel free to brainstorm and present an idea first before actually implementing something in full.
