### ISSUE TITLE
Contact Page: Contact Person can belong to several groups

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#172]
### Description

Currently the contact people are given a group that they belong to and are categorised as such. In general people can belong to multiple groups. Instead of adding them multiple times, we should just render them in multiple groups.

**Comment by Dekker1** [comment]
How do you mean? What groups exactly are you talking about and how are you adding them?

**Comment by fellab** [comment]
In the contact section you can add a person to a group. Some people are in several groups. Klubbmästare, ordförande, vice ordförande, samarbetskontakt and so on. The same person right now needs to be added two times.

**Comment by Dekker1** [comment]
Okay, that shouldn't require much of a change. I'll change the "group" attribute to "groups", which will be a comma separated list of groups the user belongs to.
