### ISSUE TITLE
Using an already added person

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#173]
### Description

When adding persons on other pages than the contact page it would be way easier for future editing if you only could use persons from the actual contact page. Say that I add Klubbmästare in contacts and only edit it their I could just add that person on the Uthgård page. And if I edit the Klubbmästare information it gets edited on Uthgård page automatically without having to edit it there as well. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
This would require a global storage of the people cards. Although this isn't very hard. This would be against the requirements that were discussed earlier.

A possibility would be to enable the people cards to link against a certain Role. This would even automatically update the names of the people as well. Currently the only downside of this would be that e-mails of positions would have to be included in the Roles and handling Roles were multiple people are appointed would require some attention.

**Comment by fellab** [comment]
That would be really great. A downside as you mention would be the multiple ones. But that's pretty much only the board.
