### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#174]
### Description

When adding columns they dont set up next to each other. They just go downwards. When adding two columns with the size 6 or three with the size 4 it would be nice to have them lining up next to each other. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
Columns go up to 12. After that they wrap around. Please choose relative smaller sizes for the columns. 

For more information read about the grid: http://materializecss.com/grid.html
