### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#177]
### Description

When adding logos it would be nice to able to do things with it. Adding a text or embed a link in the logo. Right now its just a logo, nothing more. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
I don't really understand where you would want to put the text so I'm going to ignore that for now. I do agree that these should be links, so I'll add a field for that.
