### ISSUE TITLE
contact page cards

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#185]
Is it possible to make the contact card the same size based on the largest card? Looks nicer than now when its different sizes.. 

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
Were are you seeing different sizes?

**Comment by fellab** [comment]
If you look at the published contact page the cards are different sizes depending on how much text the are in it.

**Comment by Dekker1** [comment]
I can't do what you are asking, but it is possible to give them a standard height.
