### ISSUE TITLE
Font color on "bildöverdrag"

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#200]
### Description

It would be nice if we could change the font color on "bildöverdrag". Almost all pictures are impossible to combine with the grey font that is today.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
It would be great if you could provide more information of what you mean. Although I could search through the Swedish translations and try to find where this string occurs, it would be a 100 times easier if you would just post the location of the page and a screenshot of the exact problem.

**Comment by fellab** [comment]
Sorry about that! It's the "picture overlay"-function. 

![image](https://user-images.githubusercontent.com/29704138/29460404-27d7bbb4-8428-11e7-90a6-e572fa4cce16.png)

**Comment by fellab** [comment]
Fixed.

**Comment by Dekker1** [comment]
@fellab No pull request seems to be submitted, this means that nothing has yet changed. So it can't be marked as fixed yet.
