### ISSUE TITLE
Social media add insta/fb/twitter and fix youtube

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#201]
### Description
It would nice to be possible to:
Instagram - adding an embed connected to our instagram
Facebook - same here as above
Twitter - same here as above

Youtube - fix the interface when you add an embed from youtube. Adding a embed now looks terrible.
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
@jsnider The new version of Wagtail should help with this. Might require some testing though to see if there are any regressions
