### ISSUE TITLE
Responsive image

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#205]
### Description

Even though I have a 100 px height picture and want the whole of it to show by choosing that the picture height should be 100 px it zooms in on the picture.

![image](https://user-images.githubusercontent.com/29704138/29820366-861fc8e8-8cc4-11e7-8ee3-67bbcc42bceb.png)

This shouldn't be the case. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
I don't understand what you mean. Please explain more clearly what the current situation is, what you would expect to be the case, and what you would see as the solution.

**Comment by furedal** [comment]
Solved in #262
