### ISSUE TITLE
Logged in features

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#206]
### Description

Is it possible to have pages that are hidden for people that aren't logged in?
If not, could we make it possible? 
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by Dekker1** [comment]
![screen shot 2017-08-29 at 15 19 31](https://user-images.githubusercontent.com/1564252/29822940-7ae86ac6-8ccd-11e7-8a08-b6b9dc40889a.png)
Click this in the top of the editing interface
