### ISSUE TITLE
Contact cards zoomed in

### ISSUE THREAD

**Issue by fellab** [UTNkar/moore#210]
### Description

Contact cards do not adapt to the site when used on a mobile device. It looks really bad.
![image](https://user-images.githubusercontent.com/29704138/30273565-ce4804a2-96f9-11e7-9184-3e00171ceb65.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Comment by furedal** [comment]
solved in #205
