### ISSUE TITLE
Unable to verify my email when creating superuser

### ISSUE THREAD

**Issue by dakaza98** [UTNkar/moore#260]
### Description

When I try to create a superuser at moore.utn.se i fill in my credentials and finally get an email template with a link. The mail doesn't get sent to my email and the link that is given is a local link (127.0.0.1:8000/{path to verification} so i must go to it from the terminal at moore.utn.se. When I do that i get an error saying connection refused. I can't verify my email so there for i can't get my admin account. I'm probably doing something wrong but i can't find anywhere how to do it right. How do I do it?

### Steps to Reproduce

1. ssh to moore.utn.se
2. go to /var/www/moore
3. run source source_me.sh
4. go to src and run ./manage.py createsuperuser
5. fill in credidentials
6. get an email template with the verification link
7. run cURL on that link
8. get error: connection refused

**Comment by furedal** [comment]
Hey, before entering the link, have you started your local server?

```./manage.py runserver```

**Comment by dakaza98** [comment]
I ran the command again because i don't have the link still. I now get an error after i have typed in all the credidentials saying "attempt to write a readonly database". I tried using the moore ansible book but I still get that error.

**Comment by Dekker1** [comment]
Please don't fiddle around with the live setup on Moore unless you really know what you're doing. The `source_me.sh` file only sets up Moore for the development version (on you own computer). It will not set all the environment variables necessary to access Moore on the server from the command line.

The easiest way (and only supported way) to setup an admin account on the live website is by having another admin create on using the admin interface.

**Comment by dakaza98** [comment]
Alright! I will ask Johan
