### ISSUE TITLE
Django secret key stored in plain-text on GitHub

### ISSUE THREAD

**Issue by albinantti** [UTNkar/moore#520]
### Description

Django secret key for production is stored in plain text in the django settings file. With UTNkar becoming public, this is a huge issue assuming the secret key is the one actually used. 

https://github.com/UTNkar/moore/blob/b6edc0eb72c75b2e3a6572ed1a9a3c5f6c305396/src/moore/settings/production.py#L21-L25

**Comment by dakaza98** [comment]
The key that is put there is a default value incase the environment variable does not exist. It is not the actual key that is being used
