### ISSUE TITLE
Hem/Home button in top navigation does not redirect to utn.se

### ISSUE THREAD

**Issue by Antonfogelberg** [UTNkar/moore#553]
When clicking the Uppsala teknolog och-naturvetarkår logo the user should be redirected to utn.se.

The home button could still redirect the user to the home page of the specific committee page.

**Comment by dakaza98** [comment]
That is intentional, the point of the logo is that it should bring you to the start page of the current page. However the logo does make it confusing since it is the utn logo. This issue is mentioned in #469 that it would be better if you could change that logo

**Comment by Antonfogelberg** [comment]
It sure is confusing and a bit redundant with a "Home" button and the union logo. However I think it would be good to have a easy way to navigate back to utn.se. Will continue to think about this issue!

**Comment by dakaza98** [comment]
It's a common design in web development that you have it this way. The logo is primarily there to show your brand but many developers put a link to the startpage since many uses tend to associate the logo with the startpage
