### ISSUE TITLE
Add GDPR-button

### ISSUE THREAD

**Issue by JohanAnderssonOstling** [UTNkar/moore#649]
A button where applicants can consent to their personal data being stored have to be added in the application form to ensure compliance with GDPR.

Swedish text: "Jag godkänner att mina uppgifter sparas i enlighet med Uppsala teknolog- och naturvetarkårs integritetspolicy som går att hitta på https://www.utn.se/sv/dokument"

English text: "I accept that my data is saved in accordance with Uppsala Union of Engineering and Science Students' integrity policy that can be found at https://www.utn.se/about-union/document-archive/"

**Comment by Marmingen** [comment]
Issue fixed
