### ISSUE TITLE
Go through all languages files

### ISSUE THREAD

**Issue by dakaza98** [UTNkar/moore#730]
Many of our languages files are filled with old translations, translations that are not being used, translations that are being fuzzy. It would be a good idea to go through them all with [poedit](https://poedit.net/) and do a spring cleaning in all of them

**Comment by Marmingen** [comment]
@blyvil you should be able to do this despite having trouble with setting up a local version

**Comment by blyvil** [comment]
Went through remaining translations, pushed to branch.
